import type { Product } from "@/lib/types";

const img = (id: string, alt: string) => ({
  id,
  url: `https://images.unsplash.com/${id}?w=1000&q=75&auto=format&fit=crop`,
  alt,
});

export const products: Product[] = [
  {
    id: "p-tao-envy",
    sku: "TAO-ENVY-001",
    slug: "tao-envy-new-zealand",
    name: "Táo Envy New Zealand",
    categoryId: "cat-tao",
    price: 89000,
    salePrice: 75000,
    stock: 120,
    unit: "kg",
    origin: "New Zealand",
    season: "Quanh năm",
    isOrganic: false,
    isFeatured: true,
    images: [
      img("photo-1560806887-1e4cd0b6cbd6", "Táo Envy New Zealand đỏ mọng"),
      img("photo-1619546813926-a78fa6372cd2", "Táo Envy bổ đôi"),
    ],
    description:
      "Táo Envy New Zealand nổi tiếng với vị ngọt thanh, giòn tan, vỏ đỏ hồng bắt mắt. Được tuyển chọn từ những vườn táo cao cấp, đảm bảo tươi ngon khi đến tay khách hàng.",
    nutrition: [
      { label: "Năng lượng", value: "52 kcal/100g" },
      { label: "Chất xơ", value: "2.4g/100g" },
      { label: "Vitamin C", value: "4.6mg/100g" },
      { label: "Kali", value: "107mg/100g" },
    ],
    weight: "3-4 trái/kg",
    expiry: "14 ngày bảo quản lạnh",
    rating: 4.8,
    reviewCount: 156,
    soldCount: 892,
    createdAt: "2026-05-10",
    tags: ["ban-chay", "khuyen-mai"],
  },
  {
    id: "p-tao-fuji",
    sku: "TAO-FUJI-002",
    slug: "tao-fuji-nhat-ban",
    name: "Táo Fuji Nhật Bản",
    categoryId: "cat-tao",
    price: 145000,
    stock: 60,
    unit: "kg",
    origin: "Nhật Bản",
    season: "Thu",
    isOrganic: true,
    isFeatured: false,
    images: [img("photo-1619546813926-a78fa6372cd2", "Táo Fuji Nhật Bản")],
    description:
      "Táo Fuji Nhật Bản hữu cơ, trồng theo tiêu chuẩn khắt khe, vị ngọt đậm đà, giòn mọng nước, thích hợp làm quà biếu cao cấp.",
    nutrition: [
      { label: "Năng lượng", value: "58 kcal/100g" },
      { label: "Chất xơ", value: "2.1g/100g" },
      { label: "Vitamin C", value: "5mg/100g" },
    ],
    weight: "2-3 trái/kg",
    expiry: "20 ngày bảo quản lạnh",
    rating: 4.9,
    reviewCount: 68,
    soldCount: 210,
    createdAt: "2026-06-01",
    tags: ["huu-co", "moi"],
  },
  {
    id: "p-cam-sanh",
    sku: "CAM-SANH-003",
    slug: "cam-sanh-vietnam",
    name: "Cam sành Việt Nam",
    categoryId: "cat-cam",
    price: 39000,
    salePrice: 32000,
    stock: 200,
    unit: "kg",
    origin: "Việt Nam",
    season: "Quanh năm",
    isOrganic: false,
    isFeatured: true,
    images: [img("photo-1547514701-42782101795e", "Cam sành Việt Nam")],
    description:
      "Cam sành trồng tại miền Tây Nam Bộ, vỏ xanh mọng, ruột vàng cam, vị ngọt thanh xen chua nhẹ, giàu vitamin C, thích hợp ép nước mỗi ngày.",
    nutrition: [
      { label: "Năng lượng", value: "47 kcal/100g" },
      { label: "Vitamin C", value: "53mg/100g" },
      { label: "Chất xơ", value: "2.4g/100g" },
    ],
    weight: "4-5 trái/kg",
    expiry: "10 ngày bảo quản mát",
    rating: 4.6,
    reviewCount: 312,
    soldCount: 1540,
    createdAt: "2026-04-20",
    tags: ["ban-chay", "khuyen-mai"],
  },
  {
    id: "p-cam-uc",
    sku: "CAM-UC-004",
    slug: "cam-vang-uc",
    name: "Cam vàng Úc",
    categoryId: "cat-cam",
    price: 99000,
    stock: 80,
    unit: "kg",
    origin: "Úc",
    season: "Đông",
    isOrganic: false,
    isFeatured: false,
    images: [img("photo-1611080626919-7cf5a9dbab5b", "Cam vàng Úc")],
    description:
      "Cam vàng nhập khẩu từ Úc, quả to đều, mọng nước, vị ngọt đậm, vỏ mỏng dễ bóc — lựa chọn lý tưởng để ăn trực tiếp.",
    nutrition: [
      { label: "Năng lượng", value: "45 kcal/100g" },
      { label: "Vitamin C", value: "50mg/100g" },
    ],
    weight: "3-4 trái/kg",
    expiry: "14 ngày bảo quản mát",
    rating: 4.7,
    reviewCount: 94,
    soldCount: 430,
    createdAt: "2026-05-28",
    tags: ["moi"],
  },
  {
    id: "p-nho-den",
    sku: "NHO-DEN-005",
    slug: "nho-den-khong-hat-my",
    name: "Nho đen không hạt Mỹ",
    categoryId: "cat-nho",
    price: 159000,
    salePrice: 129000,
    stock: 70,
    unit: "kg",
    origin: "Mỹ",
    season: "Quanh năm",
    isOrganic: false,
    isFeatured: true,
    images: [img("photo-1596363505729-4190a9506133", "Nho đen không hạt Mỹ")],
    description:
      "Nho đen không hạt nhập khẩu trực tiếp từ Mỹ, chùm to đều, vị ngọt sắc, giòn mọng — món ăn vặt yêu thích của cả gia đình.",
    nutrition: [
      { label: "Năng lượng", value: "69 kcal/100g" },
      { label: "Vitamin K", value: "14.6µg/100g" },
      { label: "Chất chống oxy hóa", value: "Cao" },
    ],
    weight: "500g/hộp",
    expiry: "10 ngày bảo quản lạnh",
    rating: 4.8,
    reviewCount: 201,
    soldCount: 760,
    createdAt: "2026-06-05",
    tags: ["ban-chay", "khuyen-mai"],
  },
  {
    id: "p-nho-xanh",
    sku: "NHO-XANH-006",
    slug: "nho-xanh-khong-hat-nam-phi",
    name: "Nho xanh không hạt Nam Phi",
    categoryId: "cat-nho",
    price: 135000,
    stock: 55,
    unit: "kg",
    origin: "Nam Phi",
    season: "Quanh năm",
    isOrganic: false,
    isFeatured: false,
    images: [img("photo-1537640538966-79f369143f8f", "Nho xanh không hạt")],
    description:
      "Nho xanh không hạt nhập khẩu Nam Phi, vị ngọt thanh mát, quả căng mọng, phù hợp cho cả trẻ nhỏ và người lớn tuổi.",
    nutrition: [
      { label: "Năng lượng", value: "67 kcal/100g" },
      { label: "Vitamin C", value: "3.2mg/100g" },
    ],
    weight: "500g/hộp",
    expiry: "10 ngày bảo quản lạnh",
    rating: 4.6,
    reviewCount: 88,
    soldCount: 320,
    createdAt: "2026-05-15",
    tags: ["moi"],
  },
  {
    id: "p-xoai-cat",
    sku: "XOAI-CAT-007",
    slug: "xoai-cat-hoa-loc",
    name: "Xoài cát Hòa Lộc",
    categoryId: "cat-xoai",
    price: 79000,
    stock: 150,
    unit: "kg",
    origin: "Việt Nam",
    season: "Hạ",
    isOrganic: true,
    isFeatured: true,
    images: [img("photo-1605027990121-cbae9e0642df", "Xoài cát Hòa Lộc chín vàng")],
    description:
      "Xoài cát Hòa Lộc đặc sản Tiền Giang, thịt vàng óng, hạt lép, vị ngọt đậm thơm lừng — được mệnh danh là 'nữ hoàng các loại xoài Việt'.",
    nutrition: [
      { label: "Năng lượng", value: "60 kcal/100g" },
      { label: "Vitamin A", value: "54µg/100g" },
      { label: "Vitamin C", value: "36mg/100g" },
    ],
    weight: "2-3 trái/kg",
    expiry: "7 ngày ở nhiệt độ thường",
    rating: 4.9,
    reviewCount: 267,
    soldCount: 980,
    createdAt: "2026-06-10",
    tags: ["huu-co", "ban-chay"],
  },
  {
    id: "p-xoai-thai",
    sku: "XOAI-THAI-008",
    slug: "xoai-thai-keo",
    name: "Xoài Thái keo",
    categoryId: "cat-xoai",
    price: 55000,
    salePrice: 45000,
    stock: 140,
    unit: "kg",
    origin: "Thái Lan",
    season: "Quanh năm",
    isOrganic: false,
    isFeatured: false,
    images: [img("photo-1601493700631-2b16ec4b4716", "Xoài Thái keo giòn")],
    description:
      "Xoài Thái keo giòn ngọt, ăn xanh chấm muối ớt hoặc để chín ăn đều ngon, năng suất cao và giá cả phải chăng.",
    nutrition: [
      { label: "Năng lượng", value: "58 kcal/100g" },
      { label: "Vitamin C", value: "28mg/100g" },
    ],
    weight: "2-3 trái/kg",
    expiry: "7 ngày ở nhiệt độ thường",
    rating: 4.5,
    reviewCount: 143,
    soldCount: 670,
    createdAt: "2026-05-02",
    tags: ["khuyen-mai"],
  },
  {
    id: "p-cherry-my",
    sku: "CHERRY-MY-009",
    slug: "cherry-do-my",
    name: "Cherry đỏ Mỹ size 9.5",
    categoryId: "cat-cherry",
    price: 399000,
    salePrice: 349000,
    stock: 40,
    unit: "kg",
    origin: "Mỹ",
    season: "Hạ",
    isOrganic: false,
    isFeatured: true,
    images: [img("photo-1528821128474-27f963b062bf", "Cherry đỏ Mỹ")],
    description:
      "Cherry đỏ Mỹ size 9.5 (cỡ lớn), quả đều, đỏ mọng, vị ngọt đậm xen chút chua thanh — hàng không chính hãng, có tem nhập khẩu.",
    nutrition: [
      { label: "Năng lượng", value: "63 kcal/100g" },
      { label: "Chất chống oxy hóa", value: "Rất cao" },
      { label: "Vitamin C", value: "7mg/100g" },
    ],
    weight: "1kg/hộp",
    expiry: "7 ngày bảo quản lạnh",
    rating: 4.9,
    reviewCount: 189,
    soldCount: 540,
    createdAt: "2026-06-12",
    tags: ["ban-chay", "khuyen-mai"],
  },
  {
    id: "p-cherry-uc",
    sku: "CHERRY-UC-010",
    slug: "cherry-vang-uc",
    name: "Cherry vàng Úc",
    categoryId: "cat-cherry",
    price: 459000,
    stock: 25,
    unit: "kg",
    origin: "Úc",
    season: "Đông",
    isOrganic: false,
    isFeatured: false,
    images: [img("photo-1528821128474-27f963b062bf", "Cherry vàng Úc")],
    description:
      "Cherry vàng Úc hiếm và cao cấp, vị ngọt thanh tao, ít chua, thích hợp làm quà biếu sang trọng dịp lễ Tết.",
    nutrition: [
      { label: "Năng lượng", value: "60 kcal/100g" },
      { label: "Vitamin A", value: "3µg/100g" },
    ],
    weight: "1kg/hộp",
    expiry: "7 ngày bảo quản lạnh",
    rating: 4.8,
    reviewCount: 42,
    soldCount: 110,
    createdAt: "2026-06-08",
    tags: ["moi"],
  },
  {
    id: "p-kiwi-vang",
    sku: "KIWI-VANG-011",
    slug: "kiwi-vang-new-zealand",
    name: "Kiwi vàng New Zealand",
    categoryId: "cat-kiwi",
    price: 89000,
    stock: 90,
    unit: "kg",
    origin: "New Zealand",
    season: "Quanh năm",
    isOrganic: false,
    isFeatured: false,
    images: [img("photo-1585059895524-72359e06133a", "Kiwi vàng New Zealand")],
    description:
      "Kiwi vàng Zespri chính hãng New Zealand, ruột vàng óng, vị ngọt đậm ít chua, giàu vitamin C gấp đôi kiwi xanh thông thường.",
    nutrition: [
      { label: "Năng lượng", value: "61 kcal/100g" },
      { label: "Vitamin C", value: "161mg/100g" },
      { label: "Chất xơ", value: "1.4g/100g" },
    ],
    weight: "6-7 trái/kg",
    expiry: "14 ngày bảo quản mát",
    rating: 4.8,
    reviewCount: 176,
    soldCount: 620,
    createdAt: "2026-05-20",
    tags: ["ban-chay"],
  },
  {
    id: "p-kiwi-xanh",
    sku: "KIWI-XANH-012",
    slug: "kiwi-xanh-y",
    name: "Kiwi xanh Ý",
    categoryId: "cat-kiwi",
    price: 75000,
    salePrice: 65000,
    stock: 100,
    unit: "kg",
    origin: "Ý",
    season: "Quanh năm",
    isOrganic: false,
    isFeatured: false,
    images: [img("photo-1585059895524-72359e06133a", "Kiwi xanh Ý")],
    description:
      "Kiwi xanh nhập khẩu từ Ý, vị chua ngọt hài hòa, giàu chất xơ và vitamin, hỗ trợ tiêu hóa tốt.",
    nutrition: [
      { label: "Năng lượng", value: "61 kcal/100g" },
      { label: "Vitamin C", value: "93mg/100g" },
    ],
    weight: "7-8 trái/kg",
    expiry: "14 ngày bảo quản mát",
    rating: 4.6,
    reviewCount: 98,
    soldCount: 380,
    createdAt: "2026-04-28",
    tags: ["khuyen-mai"],
  },
  {
    id: "p-sau-rieng-ri6",
    sku: "SR-RI6-013",
    slug: "sau-rieng-ri6",
    name: "Sầu riêng Ri6 cơm vàng hạt lép",
    categoryId: "cat-sau-rieng",
    price: 159000,
    stock: 45,
    unit: "kg",
    origin: "Việt Nam",
    season: "Hạ",
    isOrganic: false,
    isFeatured: true,
    images: [img("photo-1526318472351-c75fcf070305", "Sầu riêng Ri6")],
    description:
      "Sầu riêng Ri6 Bến Tre cơm vàng hạt lép, béo ngậy, thơm nồng đặc trưng, được chọn lọc chín cây tự nhiên.",
    nutrition: [
      { label: "Năng lượng", value: "147 kcal/100g" },
      { label: "Chất béo", value: "5.3g/100g" },
      { label: "Kali", value: "436mg/100g" },
    ],
    weight: "2-4kg/trái",
    expiry: "3-5 ngày ở nhiệt độ thường",
    rating: 4.9,
    reviewCount: 320,
    soldCount: 1120,
    createdAt: "2026-06-15",
    tags: ["ban-chay"],
  },
  {
    id: "p-sau-rieng-musang",
    sku: "SR-MSK-014",
    slug: "sau-rieng-musang-king",
    name: "Sầu riêng Musang King Malaysia",
    categoryId: "cat-sau-rieng",
    price: 349000,
    stock: 20,
    unit: "kg",
    origin: "Malaysia",
    season: "Hạ",
    isOrganic: false,
    isFeatured: true,
    images: [img("photo-1526318472351-c75fcf070305", "Sầu riêng Musang King")],
    description:
      "Sầu riêng Musang King nhập khẩu Malaysia — 'vua của các loại sầu riêng', cơm vàng đậm, vị đắng nhẹ hậu ngọt béo đặc trưng.",
    nutrition: [
      { label: "Năng lượng", value: "157 kcal/100g" },
      { label: "Chất béo", value: "6.1g/100g" },
    ],
    weight: "1.5-2.5kg/trái",
    expiry: "Đông lạnh giữ được 3 tháng",
    rating: 5.0,
    reviewCount: 88,
    soldCount: 240,
    createdAt: "2026-06-18",
    tags: ["moi"],
  },
  {
    id: "p-dau-dalat",
    sku: "DAU-DL-015",
    slug: "dau-tay-da-lat",
    name: "Dâu tây Đà Lạt",
    categoryId: "cat-dau",
    price: 89000,
    salePrice: 75000,
    stock: 85,
    unit: "hộp 500g",
    origin: "Việt Nam",
    season: "Đông",
    isOrganic: true,
    isFeatured: true,
    images: [img("photo-1518635017498-87f514b751ba", "Dâu tây Đà Lạt tươi")],
    description:
      "Dâu tây Đà Lạt hữu cơ, quả đỏ mọng đều, vị ngọt thanh hài hòa vị chua nhẹ, trồng trong nhà kính đạt chuẩn VietGAP.",
    nutrition: [
      { label: "Năng lượng", value: "32 kcal/100g" },
      { label: "Vitamin C", value: "59mg/100g" },
      { label: "Chất xơ", value: "2g/100g" },
    ],
    weight: "500g/hộp",
    expiry: "3-5 ngày bảo quản lạnh",
    rating: 4.7,
    reviewCount: 234,
    soldCount: 890,
    createdAt: "2026-06-02",
    tags: ["huu-co", "khuyen-mai"],
  },
  {
    id: "p-dau-hanquoc",
    sku: "DAU-HQ-016",
    slug: "dau-tay-han-quoc",
    name: "Dâu tây Hàn Quốc (Seolhyang)",
    categoryId: "cat-dau",
    price: 259000,
    stock: 30,
    unit: "hộp 500g",
    origin: "Hàn Quốc",
    season: "Đông",
    isOrganic: false,
    isFeatured: false,
    images: [img("photo-1518635017498-87f514b751ba", "Dâu tây Hàn Quốc")],
    description:
      "Dâu tây giống Seolhyang nhập khẩu Hàn Quốc, quả to, mọng nước, vị ngọt đậm đà nổi tiếng, ít hạt.",
    nutrition: [
      { label: "Năng lượng", value: "34 kcal/100g" },
      { label: "Vitamin C", value: "62mg/100g" },
    ],
    weight: "500g/hộp",
    expiry: "3-5 ngày bảo quản lạnh",
    rating: 4.9,
    reviewCount: 76,
    soldCount: 198,
    createdAt: "2026-06-20",
    tags: ["moi"],
  },
  {
    id: "p-combo-thap-qua",
    sku: "COMBO-TQ-017",
    slug: "combo-thap-qua-cao-cap",
    name: "Combo tháp trái cây cao cấp",
    categoryId: "cat-combo",
    price: 899000,
    salePrice: 749000,
    stock: 15,
    unit: "tháp",
    origin: "Nhiều xuất xứ",
    season: "Quanh năm",
    isOrganic: false,
    isFeatured: true,
    images: [img("photo-1610832958506-aa56368176cf", "Tháp trái cây cao cấp")],
    description:
      "Tháp trái cây nhập khẩu cao cấp gồm táo Envy, nho đen Mỹ, cherry, kiwi vàng — trang trí sang trọng, phù hợp biếu tặng khai trương, tân gia.",
    nutrition: [{ label: "Thành phần", value: "6-8 loại trái cây theo mùa" }],
    weight: "~4-5kg",
    expiry: "5-7 ngày bảo quản lạnh",
    rating: 4.9,
    reviewCount: 54,
    soldCount: 130,
    createdAt: "2026-06-22",
    tags: ["combo", "khuyen-mai"],
  },
  {
    id: "p-combo-gio-qua",
    sku: "COMBO-GQ-018",
    slug: "gio-qua-suc-khoe",
    name: "Giỏ quà trái cây sức khỏe",
    categoryId: "cat-combo",
    price: 599000,
    stock: 25,
    unit: "giỏ",
    origin: "Nhiều xuất xứ",
    season: "Quanh năm",
    isOrganic: false,
    isFeatured: false,
    images: [img("photo-1573246123716-6b1782bfc499", "Giỏ quà trái cây")],
    description:
      "Giỏ quà trái cây thăm bệnh, biếu sức khỏe gồm cam Úc, táo Fuji, nho xanh, kiwi — đóng gói trang nhã kèm thiệp chúc mừng.",
    nutrition: [{ label: "Thành phần", value: "5 loại trái cây tươi" }],
    weight: "~3kg",
    expiry: "5-7 ngày bảo quản lạnh",
    rating: 4.8,
    reviewCount: 61,
    soldCount: 175,
    createdAt: "2026-05-30",
    tags: ["combo"],
  },
  {
    id: "p-nuoc-ep-cam",
    sku: "NE-CAM-019",
    slug: "nuoc-ep-cam-nguyen-chat",
    name: "Nước ép cam nguyên chất",
    categoryId: "cat-nuoc-ep",
    price: 45000,
    stock: 60,
    unit: "chai 350ml",
    origin: "Việt Nam",
    season: "Quanh năm",
    isOrganic: false,
    isFeatured: true,
    images: [img("photo-1613478223719-2ab802602423", "Nước ép cam nguyên chất")],
    description:
      "Nước ép cam sành ép lạnh nguyên chất 100%, không đường, không chất bảo quản, giữ trọn vitamin C tự nhiên.",
    nutrition: [
      { label: "Năng lượng", value: "45 kcal/100ml" },
      { label: "Vitamin C", value: "50mg/100ml" },
    ],
    weight: "350ml/chai",
    expiry: "3 ngày bảo quản lạnh 2-4°C",
    rating: 4.7,
    reviewCount: 145,
    soldCount: 680,
    createdAt: "2026-06-01",
    tags: ["ban-chay"],
  },
  {
    id: "p-nuoc-ep-thapcam",
    sku: "NE-TC-020",
    slug: "nuoc-ep-thap-cam-detox",
    name: "Nước ép thập cẩm detox",
    categoryId: "cat-nuoc-ep",
    price: 55000,
    salePrice: 45000,
    stock: 50,
    unit: "chai 350ml",
    origin: "Việt Nam",
    season: "Quanh năm",
    isOrganic: true,
    isFeatured: false,
    images: [img("photo-1610970881699-44a5587cabec", "Nước ép detox thập cẩm")],
    description:
      "Nước ép detox từ táo, cần tây, dứa, chanh — công thức thanh lọc cơ thể, hỗ trợ giảm cân, đẹp da.",
    nutrition: [
      { label: "Năng lượng", value: "38 kcal/100ml" },
      { label: "Chất xơ", value: "1.2g/100ml" },
    ],
    weight: "350ml/chai",
    expiry: "3 ngày bảo quản lạnh 2-4°C",
    rating: 4.6,
    reviewCount: 92,
    soldCount: 410,
    createdAt: "2026-06-14",
    tags: ["huu-co", "khuyen-mai"],
  },
];

export function getProductBySlug(slug: string) {
  return products.find((p) => p.slug === slug);
}

export function getProductsByCategory(categoryId: string) {
  return products.filter((p) => p.categoryId === categoryId);
}

export function getRelatedProducts(product: Product, limit = 4) {
  return products
    .filter((p) => p.categoryId === product.categoryId && p.id !== product.id)
    .slice(0, limit);
}

export const origins = Array.from(new Set(products.map((p) => p.origin))).sort();
